# Generated by Django 2.0 on 2017-12-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(blank=True, null=True, verbose_name='Original URL')),
                ('short_code', models.TextField(blank=True, null=True, verbose_name='Short code')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='URL time of creation')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Clicks')),
            ],
            options={
                'verbose_name': 'Short URL',
                'verbose_name_plural': 'Short URLS',
                'db_table': 'short_urls',
            },
        ),
    ]
